# =============================================
# Jekyll configuration
# =============================================

# Where things are
source:                 source
destination:            build
layouts_dir:            _jekyll/_layouts
includes_dir:           _jekyll/_includes
data_dir:               _jekyll/_data

exclude:                assets

# Outputting
defaults:
  - scope:
      path:             ''
    values:
      layout:           base

permalink:              pretty